### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [xjhofernandes/vue-bitcoin-backend#1]
Hi,<br><br>url : https://github.com/xjhofernandes/vue-bitcoin-backend/blob/c8e494be384d5230b43e28555672db8b29b86fa7/repository/MongoDbAcess.py <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by xjhofernandes** [comment]
Hello, Shay! Thanks for the tip. The bitcoin-vue it's just a project to test things. But thanks!

I adjusted the mongo url and delete from the .py file. And i create enviroment variables to have the link.

I'm closing this issue and again thanks so much! 

Bye bye! ;)
